# mattsbackend/build.py
from pathlib import Path
from setuptools.build_meta import build_wheel as _build_wheel
from setuptools.build_meta import build_sdist as _build_sdist

def build_wheel(wheel_directory, config_settings=None, metadata_directory=None):
    print("Matthews Custom build_wheel called")

    # Create a new matthew.py file in each package
    root_dir = Path(__file__).parent
    for package_dir in root_dir.glob("**/"):
        if (package_dir / "__init__.py").exists():
            # This is a Python package
            matthew_file = package_dir / "matthew.py"
            if not matthew_file.exists():
                # Create a new file with some default content
                matthew_file.write_text(
                    "# Auto-generated by mattbackend build\n"
                    "def hello():\n"
                    "    print('Matthew was HERE!')\n"
                )
                print(f"Created {matthew_file} in package {package_dir.name}")

    return _build_wheel(wheel_directory, config_settings, metadata_directory)


def build_sdist(sdist_directory, config_settings=None):
    print("Matthews Custom build_sdist called")
    return _build_sdist(sdist_directory, config_settings)